import type {
  BudgetLine,
  ContingencyCard,
  DailyPlan,
  EventItem,
  PackingItem,
  PreTripTodo,
  RouteBlueprint,
} from "./_types";

type SeedEvent = Omit<EventItem, "id">;
type SeedRoute = Omit<RouteBlueprint, "id">;
type SeedBudget = Omit<BudgetLine, "id">;
type SeedContingency = Omit<ContingencyCard, "id">;
type SeedPacking = Omit<PackingItem, "id">;
type SeedTodo = Omit<PreTripTodo, "id" | "done">;

/**
 * Events — the master NYC calendar Jun 9–17, 2026.
 */
export const SEED_EVENTS: SeedEvent[] = [
  // — Jun 9 (Tue), arrival day
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-09",
    day: "Tue",
    time: "5:00 PM",
    title: "ITAA Brooklyn meeting",
    location: "N Brooklyn Recovery, 304 Boerum St (Morgan L)",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://internetaddictsanonymous.org/in-person-meetings/",
    notes: "Skip — repeats Jun 16. Don't overload red-eye day.",
  },
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-09",
    day: "Tue",
    time: "7:00–9:30 PM",
    title: "NYC HealthTech & MedTech Networking",
    location: "Eastpoint Bar, 25 Avenue B",
    cost: "$7.50",
    tier: "base",
    registration: "Required",
    link: "https://www.eventbrite.com/e/medtech-startups-investors-innovators-networking-event-nyc-tickets-1988351361447",
    notes: "Picked over Tech Startups (healthtech peers).",
  },
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-09",
    day: "Tue",
    time: "7:00–10:00 PM",
    title: "NYC Tech Startups Networking (Elevator Pitch)",
    location: "The Laurels, 231 2nd Ave",
    cost: "TBD on Eventbrite",
    tier: "base",
    registration: "Required",
    link: "https://www.eventbrite.com/e/nyc-tech-startups-investors-innovators-networking-with-elevator-pitch-tickets-1988826902804",
    notes: "Skip — conflicts with MedTech.",
  },
  // — Jun 10 (Wed)
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-10",
    day: "Wed",
    time: "Afternoon",
    title: "The Writers Room (loiter outreach)",
    location: "740 Broadway, Greenwich Village (entrance + Astor Place cafés)",
    cost: "Free outside; membership only inside",
    tier: "base",
    registration: "Walk-in",
    link: "https://www.writersroom.org/",
    notes: "Anytime drop-in venue; skeleton slot is Wed PM.",
  },
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-10",
    day: "Wed",
    time: "12:00 PM",
    title: "Silent Book Club — Bronx BookWorms",
    location: "Nefer Bookcafé, 694 E 241 St, Bronx",
    cost: "Free",
    tier: "T2",
    registration: "Soft RSVP",
    link: "https://www.meetup.com/silentbookclubnyc/",
    notes: "Skip — Bronx too far.",
  },
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-10",
    day: "Wed",
    time: "6:00 PM",
    title: "Quiet Reading",
    location: "Jefferson Market Library, Greenwich Village",
    cost: "Free",
    tier: "T2",
    registration: "Walk-in",
    link: "https://quietreading.org/",
    notes: "Stacks with Writers Room day.",
  },
  // — Jun 11 (Thu)
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-11",
    day: "Thu",
    time: "7:00 PM",
    title: "TMIRCE running club",
    location: "Williamsburg Bridge → ABC Beer Co",
    cost: "Free",
    tier: "T4",
    registration: "Soft RSVP",
    link: "https://www.meetup.com/nyc-informal-running-club-home-of-tmirce-nyc/",
    notes: "Optional — adjacent crowd.",
  },
  // — Jun 12 (Fri)
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-12",
    day: "Fri",
    time: "Open hours",
    title: "The Center for Fiction Day Pass",
    location: "15 Lafayette Ave, Downtown Brooklyn",
    cost: "Verify price on site (403'd)",
    tier: "base",
    registration: "Required",
    link: "https://centerforfiction.org/shop/day-pass/",
    notes: "Anytime drop-in; skeleton slot is Fri. Confirm Fri is an open day.",
  },
  // — Jun 13 (Sat)
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-13",
    day: "Sat",
    time: "2:00–3:00 PM",
    title: "ITAA Manhattan meeting",
    location: "LGBT Center, 208 W 13th St",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://internetaddictsanonymous.org/in-person-meetings/",
    notes: "Mingle on sidewalk after.",
  },
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-13",
    day: "Sat",
    time: "Afternoon",
    title: "Quiet Reading",
    location: "Nook, Bushwick",
    cost: "Free",
    tier: "T2",
    registration: "Walk-in",
    link: "https://quietreading.org/",
  },
  // — Jun 14 (Sun) — Recovery Crawl
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-14",
    day: "Sun",
    time: "11:00 AM–12:00 PM",
    title: "SLAA City Lights Sunday",
    location: "336 W 37th St, Manhattan",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://www.slaany.org/inpersonmeetings",
    notes: "Recovery Crawl: start.",
  },
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-14",
    day: "Sun",
    time: "12:30–2:30 PM",
    title: "Silent Book Club of Death",
    location: "The Met Cloisters",
    cost: "Free w/ Met admission",
    tier: "T2",
    registration: "Ticket required",
    link: "https://engage.metmuseum.org/events/education/talks/cloisters/free-talks/fy26/silent-book-club-cloisters-may/",
    notes: "Skip — too far uptown.",
  },
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-14",
    day: "Sun",
    time: "3:00–4:30 PM",
    title: "SLAA Women's Meeting",
    location: "St. Francis of Assisi, 135 W 31st St",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://www.slaany.org/inpersonmeetings",
    notes: "Skip — women only.",
  },
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-14",
    day: "Sun",
    time: "4:00–5:30 PM",
    title: "SLAA Men's Qualification",
    location: "Church of the Blessed Sacrament, 152 W 71st St",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://www.slaany.org/inpersonmeetings",
    notes: "Recovery Crawl: mid.",
  },
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-14",
    day: "Sun",
    time: "5:45–6:45 PM",
    title: "SAA Meeting",
    location: "St. Margaret's House, 49 Fulton St",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://nycsaa.org/meetings/",
    notes: "Skip — overlaps next.",
  },
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-14",
    day: "Sun",
    time: "6:00–7:30 PM",
    title: "SAA Meeting",
    location: "St. Francis of Assisi, 139 W 31st St",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://nycsaa.org/meetings/",
    notes: "Recovery Crawl: end.",
  },
  // — Jun 15 (Mon)
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-15",
    day: "Mon",
    time: "5:30–6:30 PM",
    title: 'ITAA — "It Works if You Work It"',
    location: "St. Vincent Ferrer Church, 869 Lexington Ave",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://internetaddictsanonymous.org/in-person-meetings/",
    notes: "Picked over SAA (broader screen-addiction fit).",
  },
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-15",
    day: "Mon",
    time: "5:30–6:30 PM",
    title: "SAA Speaker Meeting",
    location: "NYC Service Org Office, 265 W 37th St",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://nycsaa.org/meetings/",
    notes: "Skip — conflicts with ITAA.",
  },
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-15",
    day: "Mon",
    time: "6:30 PM",
    title: "Quiet Reading",
    location: "McCarren Park, NW corner, Williamsburg",
    cost: "Free",
    tier: "T2",
    registration: "Walk-in",
    link: "https://quietreading.org/",
    notes: "Rain/>90°F → Spritzenhaus33.",
  },
  // — Jun 16 (Tue)
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-16",
    day: "Tue",
    time: "5:00 PM",
    title: "ITAA Brooklyn meeting",
    location: "N Brooklyn Recovery, 304 Boerum St",
    cost: "Free",
    tier: "T1",
    registration: "Walk-in",
    link: "https://internetaddictsanonymous.org/in-person-meetings/",
    notes: "Last full evening.",
  },
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-16",
    day: "Tue",
    time: "Evening",
    title: "Quiet Reading",
    location: "DeKalb Library, Brooklyn",
    cost: "Free",
    tier: "T2",
    registration: "Walk-in",
    link: "https://quietreading.org/",
  },
  // — Jun 17 (Wed) — departure
  {
    picked: true,
    dateKind: "fixed",
    date: "2026-06-17",
    day: "Wed",
    time: "Morning",
    title: "Housing Works Bookstore Café (final coffee / drop-offs)",
    location: "126 Crosby St, SoHo",
    cost: "Coffee budget",
    tier: "base",
    registration: "Walk-in",
    link: "https://www.housingworks.org/locations/bookstore-cafe",
    notes: "Last item before flight.",
  },
  {
    picked: false,
    dateKind: "fixed",
    date: "2026-06-17",
    day: "Wed",
    time: "6:00 PM",
    title: "Quiet Reading",
    location: "Jefferson Market Library, Greenwich Village",
    cost: "Free",
    tier: "T2",
    registration: "Walk-in",
    link: "https://quietreading.org/",
    notes: "Skip if flight before evening.",
  },
  // — Anytime
  {
    picked: false,
    dateKind: "anytime",
    time: "11 AM–7 PM",
    title: "Bryant Park Reading Room",
    location: "Bryant Park, north side near 42nd St plaza",
    cost: "Free",
    tier: "base",
    registration: "Walk-in",
    link: "https://bryantpark.org/activities/reading-room",
    notes: "Open daily Apr–Sep — slot freely.",
  },
  // — Recurring
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Tue 7:00 AM",
    title: "North Brooklyn Runners",
    location: "Maria Hernandez Park, Bushwick",
    cost: "Free",
    tier: "T4",
    registration: "Soft RSVP",
    notes: "Tue Jun 9 or 16 — early start, tough after red-eye.",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Tue/Thu/Sun",
    title: "Brooklyn Rogues run club",
    location: "Grand Army Plaza",
    cost: "Free",
    tier: "T4",
    registration: "Soft RSVP",
    link: "https://www.brooklynrogues.org/",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Quarterly",
    title: "Pepper NYC events",
    location: "Varies",
    cost: "Varies",
    tier: "T3",
    registration: "Required",
    link: "https://luma.com/peppernyc",
    notes: "Check Luma for any June event.",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Recurring",
    title: "Pulse NYC Mental Health Tech Leaders Meetup",
    location: "Varies",
    cost: "Varies",
    tier: "T3",
    registration: "Required",
    link: "https://pulse.nyc/",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Recurring",
    title: "MedStartr NYC",
    location: "Varies",
    cost: "Varies",
    tier: "T3",
    registration: "Required",
    link: "https://www.meetup.com/health20nyc/",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "TBD",
    title: "Bio, Eco & Deep Tech Mixer (Antler/Nucleate/Coeus)",
    location: "Hidden until registration",
    cost: "Free?",
    tier: "T3",
    registration: "Required",
    link: "https://luma.com/frontierbuildersmixer",
    notes: "Apply early; address revealed on approval.",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "TBD",
    title: "Healthcare AI Professionals & Builders Night",
    location: "Hidden until registration",
    cost: "Pay-your-own",
    tier: "T3",
    registration: "Required",
    link: "https://luma.com/gkudtinh",
    notes: "Apply early; confirm June instance exists.",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Recurring",
    title: "EVRYMAN men's groups",
    location: "Varies",
    cost: "Varies",
    tier: "T4",
    registration: "Required",
    link: "https://www.evryman.com/",
    notes: "Behavior-change-aware ambitious men.",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Pop-up",
    title: "Bright Nights Social (alcohol-free pop-ups)",
    location: "Varies",
    cost: "Varies",
    tier: "T4",
    registration: "Required",
    link: "https://brightnightssocial.substack.com/",
  },
  {
    picked: false,
    dateKind: "recurring",
    cadence: "Recurring",
    title: "Choosing Zero NY (sober-curious)",
    location: "Varies",
    cost: "Varies",
    tier: "T4",
    registration: "Required",
    link: "https://www.meetup.com/new-york-sobercurious-meetup/",
  },
  // — Outside window
  {
    picked: false,
    dateKind: "outside",
    date: "2026-06-01",
    day: "Jun 1–7",
    title: "NYC Tech Week 2026 (a16z)",
    location: "Across Manhattan/Brooklyn",
    cost: "Most events free",
    tier: "T3",
    registration: "Required",
    link: "https://www.tech-week.com/calendar/nyc",
    notes: "Ends ~36 hrs before arrival — scan for Sun Jun 7 healthtech events if shifting flight.",
  },
  {
    picked: false,
    dateKind: "outside",
    date: "2026-06-18",
    day: "Thu",
    time: "6:30–7:30 PM",
    title: 'NYPL Offline Book Club ("Machine Stops")',
    location: "Stavros Niarchos Foundation Library, Rm 405",
    cost: "Free",
    tier: "base",
    registration: "Required",
    link: "https://www.nypl.org/events/programs/2026/06/18/offline-book-club-machine-stops",
    notes: "Day after departure — consider +1 day on return flight.",
  },
];

/**
 * Transit routes — door-to-door blueprints.
 */
export const SEED_ROUTES: SeedRoute[] = [
  {
    name: "Option 1 — Traffic-immune rail",
    fromTo: "Washington Park (JC) → Midtown / Bryant Park / Ace Hotel",
    totalMinutes: 35,
    totalCostUSD: 8.8,
    steps: [
      { mode: "Walk", detail: "Washington Park → 9th St / Congress St Elevator", minutes: 5 },
      { mode: "Light Rail", detail: "9th St → Hoboken Terminal (southbound)", minutes: 9, cost: 2.55 },
      { mode: "PATH", detail: "Hoboken Terminal → 33rd Street Station (Midtown)", minutes: 13, cost: 3.25 },
      { mode: "Walk", detail: "33rd St → Ace Hotel / Monarch Rooftop / Bryant Park", minutes: 8 },
    ],
    notes: "Bypasses Lincoln Tunnel entirely. Predictable.",
  },
  {
    name: "Option 1b — Rail to Greenwich Village / Writers Room",
    fromTo: "Washington Park → Writers Room (740 Broadway)",
    totalMinutes: 30,
    totalCostUSD: 5.8,
    steps: [
      { mode: "Walk", detail: "Washington Park → 9th St Elevator", minutes: 5 },
      { mode: "Light Rail", detail: "9th St → Hoboken Terminal", minutes: 9, cost: 2.55 },
      { mode: "PATH", detail: "Hoboken–33rd St line → 9th Street Station", minutes: 9, cost: 3.25 },
      { mode: "Walk", detail: "9th St Station → 740 Broadway", minutes: 7 },
    ],
  },
  {
    name: "Option 1c — Rail to Downtown Brooklyn (Center for Fiction)",
    fromTo: "Washington Park → 15 Lafayette Ave",
    totalMinutes: 50,
    totalCostUSD: 8.8,
    steps: [
      { mode: "Walk", detail: "Washington Park → 9th St Elevator", minutes: 5 },
      { mode: "Light Rail", detail: "9th St → Hoboken Terminal", minutes: 9, cost: 2.55 },
      { mode: "PATH", detail: "Hoboken–WTC line → World Trade Center", minutes: 9, cost: 3.25 },
      { mode: "Subway", detail: "Oculus → 4/5 Downtown 2 stops → Nevins Street", minutes: 8, cost: 3.0 },
      { mode: "Walk", detail: "Nevins St → 15 Lafayette Ave", minutes: 5 },
    ],
  },
  {
    name: "Option 1d — Rail to FiDi / Brookfield Place",
    fromTo: "Washington Park → World Trade Center",
    totalMinutes: 28,
    totalCostUSD: 5.8,
    steps: [
      { mode: "Walk", detail: "Washington Park → 9th St Elevator", minutes: 5 },
      { mode: "Light Rail", detail: "9th St → Hoboken Terminal", minutes: 9, cost: 2.55 },
      { mode: "PATH", detail: "Hoboken–WTC line → WTC (Oculus)", minutes: 9, cost: 3.25 },
      { mode: "Walk", detail: "Oculus → Brookfield Place via underground concourse", minutes: 3 },
    ],
  },
  {
    name: "Option 2 — Direct 123 Bus",
    fromTo: "Washington Park → Port Authority → anywhere via subway",
    totalMinutes: 30,
    totalCostUSD: 7.1,
    steps: [
      { mode: "Walk", detail: "Washington Park → 123 Bus stop", minutes: 3 },
      { mode: "Bus", detail: "NJ Transit 123 → Port Authority", minutes: 18, cost: 4.1 },
      { mode: "Subway", detail: "Port Authority → destination (OMNY-tap)", minutes: 9, cost: 3.0 },
    ],
    notes: "Faster IF tunnel is clear. Gambles on traffic. Lower cost than rail.",
  },
];

/**
 * Pre-trip budget — line items.
 */
export const SEED_BUDGET: SeedBudget[] = [
  {
    category: "Transit",
    label: "Fixed transit (rail corridor, 10 days)",
    amountUSD: 169,
    notes: "Light Rail + PATH + Subways across the trip.",
  },
  {
    category: "Emergency",
    label: "Unforeseen Uber buffer",
    amountUSD: 150,
  },
  {
    category: "Meetings",
    label: "10 in-person coffee meetings ($32 each)",
    amountUSD: 320,
    notes:
      "Spacious business cafés: Devoción Flatiron, Housing Works Bookstore, Marlton Hotel Lounge, Ace Hotel Lobby.",
  },
  {
    category: "Groceries",
    label: "10-day sandwich groceries",
    amountUSD: 100,
    notes:
      "Egg salad breakfast, Italian hero lunch, grilled cheese dinner. Bulk-buy at Supremo Food Market in JC.",
  },
  {
    category: "Food",
    label: "On-the-go snack buffer",
    amountUSD: 20,
  },
  {
    category: "Events",
    label: "NYC HealthTech MedTech ticket (Jun 9)",
    amountUSD: 7.5,
  },
  {
    category: "Events",
    label: "Center for Fiction day pass (Jun 12)",
    amountUSD: 30,
    notes: "Estimate — verify exact price on site before purchase.",
  },
];

/**
 * Contingencies — flip cards.
 */
export const SEED_CONTINGENCIES: SeedContingency[] = [
  {
    category: "Weather",
    situation: "Rain on a Quiet Reading day (Mon Jun 15 McCarren, Sat Jun 13 Nook)",
    action:
      "McCarren moves to Spritzenhaus33 (per organizer). For Nook, swap to Bryant Park Reading Room or the Writers Room loiter zone.",
  },
  {
    category: "Weather",
    situation: ">90°F day",
    action:
      "Pre-load 1L water + sandwich; pick indoor outreach venues (Brookfield Place lunch crowd, Housing Works, Ace Hotel lobby). Avoid the Quiet Reading outdoor sessions.",
  },
  {
    category: "Energy",
    situation: "Wiped out from outreach (probably Wed or Thu)",
    action:
      "Take the morning off. Recover with sandwich + Bryant Park bench. Skip first half of day's plan. Show up to evening event sharp.",
  },
  {
    category: "Energy",
    situation: "Red-eye recovery (Tue Jun 9)",
    action:
      "No daytime outreach. Sleep until noon if needed. One target only: MedTech mixer 7 PM. Skip ITAA Brooklyn 5 PM — repeats Jun 16.",
  },
  {
    category: "Conflict",
    situation: "Two events overlap on Sun Jun 14 (SAA Fulton vs SAA W 31st)",
    action: "Pick W 31st (St Francis). It has more attendees, better sidewalk for post-meeting outreach.",
  },
  {
    category: "Conflict",
    situation: "Mon Jun 15 — ITAA vs SAA both at 5:30 PM",
    action:
      "Default: ITAA (broader screen-addiction fit). Switch to SAA only if you've already attended an ITAA meeting this week and want sample variety.",
  },
  {
    category: "Transit",
    situation: "PATH delay or service interruption",
    action:
      "Pivot to 123 Bus (Option 2). Adds 5–15 min but bypasses rail. From Port Authority, OMNY-tap any subway to destination.",
  },
  {
    category: "Transit",
    situation: "Stuck in Manhattan after 11 PM",
    action:
      "Late PATH runs ~every 30 min until 4 AM but only on weekend pattern after midnight. Check schedule before evening events. Budget $40 Uber as fallback.",
  },
  {
    category: "Health",
    situation: "Sick / GI episode (foreign water + sandwich diet)",
    action:
      "Stay in JC, eat plain rice + crackers from Supremo. Cancel all meetings via Cal.com (auto). Resume next day if 24 hrs symptom-free.",
  },
  {
    category: "Outreach",
    situation: "Outreach is flopping — no one engaging at the venue",
    action:
      "Leave after 90 min. Don't grind a dead room. Pivot to Housing Works or Bryant Park where remote workers are concentrated. Log the venue in mistakes.",
  },
  {
    category: "Outreach",
    situation: "Person says yes to meet but flakes day-of",
    action:
      "Don't pursue more than once. Mark Dead in outreach app. Move on. Trip is too short for chasing.",
  },
  {
    category: "Money",
    situation: "Running over food budget by mid-trip",
    action:
      "Drop coffee meetings to 1 per 2 days. Move outreach to Bryant Park / Housing Works (no coffee purchase obligation). Tighten sandwich groceries by skipping the daily snack buffer.",
  },
];

/**
 * Packing checklist.
 */
export const SEED_PACKING: SeedPacking[] = [
  { label: "Laptop + charger", category: "Tech", checked: false },
  { label: "Phone + cable + 10000mAh power bank", category: "Tech", checked: false },
  { label: "Wired earbuds (for calls in noisy venues)", category: "Tech", checked: false },
  { label: "US-EU plug adapter (if needed)", category: "Tech", checked: false },
  { label: "Passport + COP cash for taxi home", category: "Documents", checked: false },
  { label: "Visa + Mastercard (both)", category: "Documents", checked: false },
  { label: "Printed paper backup of meeting list", category: "Documents", checked: false },
  { label: "Trip-planner workspace URL bookmarked on phone", category: "Documents", checked: false },
  { label: "1 dress shirt (for MedTech mixer Jun 9)", category: "Clothes", checked: false },
  { label: "3 t-shirts, 2 long sleeve", category: "Clothes", checked: false },
  { label: "1 sweater (NYC nights mid-June are 55–65°F)", category: "Clothes", checked: false },
  { label: "Light rain jacket", category: "Clothes", checked: false },
  { label: "Walking shoes (you'll do 10 km/day easily)", category: "Clothes", checked: false },
  { label: "Insulated lunch bag (sandwich commute)", category: "Food prep", checked: false },
  { label: "2 plastic sandwich containers", category: "Food prep", checked: false },
  { label: "Reusable water bottle", category: "Food prep", checked: false },
  { label: "Notebook + 2 pens (faster than typing at first contact)", category: "Outreach kit", checked: false },
  { label: "Business card / QR code on phone lock screen", category: "Outreach kit", checked: false },
  { label: "One-pager PDF on phone, ready to AirDrop / share", category: "Outreach kit", checked: false },
  { label: "Sandwich-week grocery list (ready for Jun 9 morning Supremo run)", category: "Outreach kit", checked: false },
  { label: "Basic toiletries", category: "Misc", checked: false },
  { label: "Advil + Pepto-Bismol", category: "Misc", checked: false },
];

/**
 * Pre-trip todos with link placeholders.
 */
export const SEED_TODOS: SeedTodo[] = [
  {
    label: "Set up Cal.com or Calendly with NYC time slots Jun 9–17, 30-min defaults",
    link: "https://cal.com/",
    dueDate: "2026-05-29",
    notes: "10 AM–6 PM windows. Buffer 30 min between slots.",
  },
  {
    label: "Write one-pager landing page link (problem → who → ask)",
    dueDate: "2026-05-30",
    notes: "Will go in every Tier 1 cold message.",
  },
  {
    label: "Build initial LinkedIn target list (50 Tier 1 + 20 Tier 2)",
    dueDate: "2026-05-31",
  },
  {
    label: "Sort phone contacts into Bucket A/B/C, send Bucket A this week",
    dueDate: "2026-06-01",
  },
  {
    label: "Apply to Bio, Eco & Deep Tech Mixer on Luma (host approval takes days)",
    link: "https://luma.com/frontierbuildersmixer",
    dueDate: "2026-05-29",
  },
  {
    label: "Apply to Healthcare AI Professionals & Builders Night on Luma",
    link: "https://luma.com/gkudtinh",
    dueDate: "2026-05-29",
  },
  {
    label: "Buy NYC HealthTech MedTech ticket ($7.50)",
    link: "https://www.eventbrite.com/e/medtech-startups-investors-innovators-networking-event-nyc-tickets-1988351361447",
    dueDate: "2026-06-01",
  },
  {
    label: "Buy Center for Fiction day pass; confirm Fri Jun 12 is an open day",
    link: "https://centerforfiction.org/shop/day-pass/",
    dueDate: "2026-06-05",
  },
  {
    label: "Decide on return-flight shift (+1 day) for NYPL Offline Book Club Jun 18",
    link: "https://www.nypl.org/events/programs/2026/06/18/offline-book-club-machine-stops",
    dueDate: "2026-06-01",
  },
  {
    label: "Send LinkedIn first wave (25 messages, Tier 1 cold template)",
    dueDate: "2026-05-30",
  },
  {
    label: "First-day grocery run plan: Supremo Food Market, Jersey City",
    dueDate: "2026-06-08",
    notes: "Eggs, mayo, mustard, bread (2 loaves), salami, pepperoni, provolone, cheddar, ham.",
  },
  {
    label: "Pre-trip clean-up of calendar; geographic-batch confirmed meetings by day",
    dueDate: "2026-06-07",
  },
  {
    label: "Print paper backup of meeting list",
    dueDate: "2026-06-08",
  },
];

/**
 * Daily plan skeleton — one per trip day.
 */
export const SEED_DAILY_PLANS: Omit<DailyPlan, "morningChecked" | "eveningChecked">[] = [
  {
    date: "2026-06-09",
    weekday: "Tue",
    headline: "Trip launch. Recover from red-eye, hit one mixer.",
    pickedEventIds: ["medtech-mixer"],
    routeId: "rail-midtown",
    budgetAllowanceUSD: 50,
    contingencyOfTheDay:
      "Red-eye recovery: no daytime outreach. Sleep until noon if needed.",
    morningPrompt:
      "Arrival check: grocery run at Supremo, sandwich prep for 10 days. One nap.",
    eveningPrompt:
      "MedTech mixer post-game: who do I want to follow up with by Wed AM?",
  },
  {
    date: "2026-06-10",
    weekday: "Wed",
    headline: "Greenwich Village day. Writers Room loiter → Quiet Reading.",
    pickedEventIds: [],
    routeId: "rail-village",
    budgetAllowanceUSD: 25,
    contingencyOfTheDay: "If energy < 5/10, skip Quiet Reading, head home early.",
    morningPrompt: "Top 3 messages I owe today (LinkedIn replies, follow-ups)?",
    eveningPrompt:
      "Writers Room contacts: who agreed to a follow-up? Log in outreach app.",
  },
  {
    date: "2026-06-11",
    weekday: "Thu",
    headline: "FiDi / Brookfield Place lunch crowd. Optional TMIRCE run 7 PM.",
    pickedEventIds: [],
    routeId: "rail-fidi",
    budgetAllowanceUSD: 25,
    contingencyOfTheDay: "Lunch crowd at Brookfield is 12–1:30 PM. Don't miss the window.",
    morningPrompt:
      "What did I learn from Wed that I should test today? (template? venue? hook?)",
    eveningPrompt: "Mistakes log: anything to record from today?",
  },
  {
    date: "2026-06-12",
    weekday: "Fri",
    headline: "Center for Fiction day. Buy pass. Real work in the silent room + 3 outreach windows.",
    pickedEventIds: ["center-for-fiction"],
    routeId: "rail-brooklyn",
    budgetAllowanceUSD: 60,
    contingencyOfTheDay:
      "Outreach flop: leave by 4 PM, head to Astor Place for evening Writers Room outreach.",
    morningPrompt:
      "What 3 concrete tasks am I doing in the silent room today? (Legitimacy + actual work.)",
    eveningPrompt:
      "5 conversations · 3 contacts · 1 alpha-test signup. Where did I land?",
  },
  {
    date: "2026-06-13",
    weekday: "Sat",
    headline: "ITAA Manhattan 2 PM. Quiet Reading Bushwick. Weekend pace.",
    pickedEventIds: ["itaa-manhattan-sat", "quiet-reading-nook"],
    routeId: "rail-village",
    budgetAllowanceUSD: 20,
    contingencyOfTheDay:
      "ITAA: never pitch inside the room. Sidewalk after only.",
    morningPrompt: "What did the week teach me about the right kind of prospect?",
    eveningPrompt: "Outreach mistakes log: weekly review.",
  },
  {
    date: "2026-06-14",
    weekday: "Sun",
    headline: "Recovery Crawl. SLAA 11 AM → SLAA Men's 4 PM → SAA 6 PM.",
    pickedEventIds: ["slaa-city-lights", "slaa-mens", "saa-w31"],
    routeId: "rail-midtown",
    budgetAllowanceUSD: 25,
    contingencyOfTheDay:
      "Four meetings = four sidewalk windows. Pace yourself; eat between.",
    morningPrompt:
      "How will I introduce myself outside the rooms today? Practice the line.",
    eveningPrompt: "Which Recovery Crawl meeting yielded the best conversation? Why?",
  },
  {
    date: "2026-06-15",
    weekday: "Mon",
    headline: "Final Monday. ITAA 5:30 → Quiet Reading McCarren 6:30.",
    pickedEventIds: ["itaa-monday", "quiet-reading-mccarren-15"],
    routeId: "rail-midtown",
    budgetAllowanceUSD: 25,
    contingencyOfTheDay: "Rain → McCarren moves to Spritzenhaus33.",
    morningPrompt: "Recommendation asks: who else can I ask before I leave?",
    eveningPrompt:
      "Two days left. Anyone I haven't met that's still worth chasing?",
  },
  {
    date: "2026-06-16",
    weekday: "Tue",
    headline: "Last full day. ITAA Brooklyn 5 PM → Quiet Reading DeKalb.",
    pickedEventIds: ["itaa-brooklyn-tue", "quiet-reading-dekalb"],
    routeId: "rail-brooklyn",
    budgetAllowanceUSD: 30,
    contingencyOfTheDay:
      "Pre-pack tonight. Don't leave the morning of departure to scramble.",
    morningPrompt: "Top 3 follow-ups I'll send tomorrow morning before flight.",
    eveningPrompt: "Did I hit the trip's main goal? What pivots for next NYC trip?",
  },
  {
    date: "2026-06-17",
    weekday: "Wed",
    headline: "Final coffee at Housing Works. Pack. Fly home.",
    pickedEventIds: ["housing-works-final"],
    routeId: "rail-village",
    budgetAllowanceUSD: 15,
    contingencyOfTheDay:
      "Flight buffer: target arriving at JFK 3 hrs before departure.",
    morningPrompt: "Send all promised follow-ups before I get on the plane.",
    eveningPrompt: "Back in JC. What's the very first thing I do back home?",
  },
];
